### ISSUE TITLE
Implement dedispersion of pulsed signals in visibilities.

### ISSUE THREAD

**Issue by danasimard** [dsa110/dsa110-issues#106]
The T3 mask should accomplish weighting & dedispersion using data weights in casa

**Comment by danasimard** [comment]
Also depends on #105 #107

**Comment by caseyjlaw** [comment]
Incoherent dedispersion and selection of on-pulse data working. Data written to MS, but assumes single time, so fixed uvw.
To do: freq-dependent uvw (via multiple-spw MS).

**Comment by caseyjlaw** [comment]
Tests show this is a small, smearing of localization. Not significant enough to justify work for now.
