### ISSUE TITLE
Automate parameter fit to optimize T3 mask parameters in T3 manager

### ISSUE THREAD

**Issue by danasimard** [dsa110/dsa110-issues#107]
* Fit burst parameters to filterbank data from T1
* Use burst parameters in mask generation

**Comment by caseyjlaw** [comment]
Wendy has burstfit working. Model time, DM, time width can be used to define mask. Currently only demonstrated by hand.

**Comment by danasimard** [comment]
To explore grid search for imaging purposes vs a more complicated search for science.

**Comment by caseyjlaw** [comment]
Waiting on verification that burst fits are good for a large sample.
T3 imaging still manual and needs parameters to be passed in by hand.
