### ISSUE TITLE
grafana 502 error

### ISSUE THREAD

**Issue by caseyjlaw** [dsa110/dsa110-issues#14]
The grafana dashboards report a 502 "Bad Gateway" error. I suspect it is related to the change from "dsamaster" to "dsahead". Is the `antmon` source still working as expected after that change?

**Comment by caseyjlaw** [comment]
Ah, and also need to update `calmon`, I suppose.

**Comment by rh-codebase** [comment]
I'll fix that up. 

-- rick

**Comment by rh-codebase** [comment]
updated sources using new hostname: dsahead. The db table are tied to the source, so only the source needs updating.
