### ISSUE TITLE
Maintain persistence of antmc threads

### ISSUE THREAD

**Issue by danasimard** [dsa110/dsa110-issues#166]

**Comment by caseyjlaw** [comment]
One solution could be to create a service to watch antmc monitor points. If they get stale, send command to restart the process.

**Comment by caseyjlaw** [comment]
Added a service and script to https://github.com/dsa110/dsa110-systemd.
The `antmc_restart` service runs a loop to look for stale ant monitor points. If older than 20 seconds, it will restart antmc and wait for 200 s to check again.
