### ISSUE TITLE
Add task in T3 to create candidate subdirectory when a candidate is "saved" and populate the appropriate level 2 data from the "operations" data

### ISSUE THREAD

**Issue by danasimard** [dsa110/dsa110-issues#172]

**Comment by danasimard** [comment]
This is mostly working (https://github.com/dsa110/dsa110-T3/commit/da204b20c5027e6c9f3440eef52f19eab16571e9) but there are only voltages for a few candidates.  Should there be voltages for all of the candidates in the candidates directory?

**Comment by caseyjlaw** [comment]
This is working well.
