### ISSUE TITLE
WebUI Account

### ISSUE THREAD

**Issue by krittisharma** [dsa110/dsa110-issues#202]
I'm a first-year grad student in Prof. Vikram's group. Please add me to the OoD list for DSA-110.

**Comment by caseyjlaw** [comment]
@rh-codebase Can you set up this new account?
Also, user `claw` also needs a password reset.

**Comment by rh-codebase** [comment]
Currently, adding, removing and or resetting webUI accounts involves restarting the webUI and any running scripts will abort. There is 1 running script:
 2023-02-20T20:27:32Z: Id: 0 User: vikramr Script: start.py Ver: v1.1.1-220-g8c09488

**Comment by rh-codebase** [comment]
Duplicate of #201 closing this and migrating contents to #201
