### ISSUE TITLE
Incorrect Masking in Polarization Calibrated Filterbanks

### ISSUE THREAD

**Issue by FrankVerdi** [dsa110/dsa110-issues#313]
When using dsa110-pol to generate polarization calibrated filterbank files, frequency channels that are assigned to be masked are instead overwritten with a constant fill value. Existing Level 3 calibrated filterbanks are affected by the issue.

**Comment by mbsherma** [comment]
@FrankVerdi Resolved in commit https://github.com/dsa110/dsa110-pol/commit/d428efdfabfd21510303715f2bb96e5b71ad86ab by setting masked values to `NaN`. I think this is the most clear way to indicate bad channels but it can be revised if needed.
