### ISSUE TITLE
tests of localization accuracy using continuum sources in voltage data. 

### ISSUE THREAD

**Issue by caseyjlaw** [dsa110/dsa110-issues#52]
Greg, Dana, Casey

* Set up command line tool to trigger voltages
* Create tool to write MS with correct tables and filled visibilities
* Trigger voltage recording on bright source

(need to add to milestone)

**Comment by danasimard** [comment]
I've added a function to create the measurement set for T3 visibilities here: https://github.com/dsa110/dsa110-calib/blob/28605871e4a26d43edc897c233418cf00f4005fb/dsacalib/ms_io.py#L45 

Greg & I still need to confirm the order of the correlation and baselines in the T3 visibilities, and write a routine that uses this to initialize the ms, then overwrites the data tables in the ms.

**Comment by danasimard** [comment]
Closing since incorporated in #66
