### ISSUE TITLE
Regular SEFD measurements

### ISSUE THREAD

**Issue by caseyjlaw** [dsa110/dsa110-issues#62]
Set up procedure to repoint ~weekly to bright source for SEFD and system health measurements.
Use WebUI scheduling feature?

**Comment by danasimard** [comment]
Requires making a longer measurement set on a good calibrator.  We can do this on the best calibrator in the current field ~ once a week, and use the same observation to monitor azimuthal pointing offsets.

Implementing automatic RFI flagging in the ms is key for automating this process.

**Comment by danasimard** [comment]
SEFD measurements from voltage dumps are turnkey.
