### ISSUE TITLE
travis-ci on new branch

### ISSUE THREAD

**Issue by VR-DSA** [dsa110/dsa110-issues#8]
I'm not sure how to get the travis-ci tests to work on a new branch of a repo! This is for the dev-casa branch of dsa110-antpos.

**Comment by caseyjlaw** [comment]
Lots of nice changes in there!
Usually travis is set up for just two branches, master and development. You can add branches by editing the .travis.yml file "branches" settings.
That said, I think it is fine just to leave the two default branches enabled for remote testing. A good pattern is to make your branch, test locally with pytest, then make a pull request on github. I'll do that now and merge your changes into the development branch.
