### ISSUE TITLE
Training T3 candidate classifier on dynamic spectra

### ISSUE THREAD

**Issue by danasimard** [dsa110/dsa110-issues#84]
* Collecting filterbank data & labels to train.

**Comment by danasimard** [comment]
* Labels using trigger dashboard are helpful.  We should try to systematically label and archive candidates going forward
* Training using beam-time plots requires saving many new triggers
* But also useful to handpick bad candidates with bad classifications to add to training set

**Comment by caseyjlaw** [comment]
Existing classifier is doing a good job. Can tune to improve purity, but not critical.
